const { v4: uuidv4 } = require("uuid");

const articles = [
  // allArticle: [
  {
    id: uuidv4(),
    title: "Does talent exist or just hardwork?",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/Hardwork_2-01_xjvkm1.jpg",
    postDate: {
      month: "January",
      day: "19",
      year: "2019",
    },
    authors: ["Leangheng Ou", "Seihakpiseth Tan"],
    category: ["personal-development"],
    content: [
      "We, humans, tend to have unique talents, and that makes us special, that is our asset. Talent is a common word that everyone knows and respects. Most people believe that talent is inborn and the special ability of a person to do something, is the gift that everyone is born with. Do you think what they believe is true? Is talent a gift that everyone gets without doing anything? If it’s true, what were all those talented footballers, basketballers, painters, and musicians doing before their talents were discovered? Were they good at nothing before they found their talents? According to our research and experience, we’ve found that talent doesn’t exist by not doing anything, also three main factors create talents within us, these crucial factors are hard work, environment, and passion.",
      "Hard work refers to the practice, it is the construction of talent. Talent wouldn’t exist in us if we didn’t do anything to achieve it. Talent isn’t a gift, it’s the reward that we receive from practicing. When we practice a lot, our skill and technique will be developed and improve, with better skill and technique, we’ll surely be able to perform better, more skillful, and professional. We’ll additionally gain a lot more experience by practicing, having a lot of experience will expand our knowledge, such as making us be able to think smarter, faster, and more flexible in various situations. Moreover, it boosts our confidence in the field of studies or occupations, it helps us per-forming better when we have strong confidence when we believe in ourselves. Lionel Messi, one of the most famous footballers in the world, five times Ballon d’Or winner, and the player who helped Bar-celona won four Champion Leagues in just 11 years (2004-2015). Messi is the player that defined as talented, gifted because he has the best dribbling skill. When we explore his past, we’ll see that Messi was a kid in Argentina who loved to play football, he started playing when he was around 5 years old, and always loved to show his dribbling skill in the field. In 2000, at the age of 13, Messi moved to Barcelona, one of the best clubs in the world, he started to improve his skill there with other talented kids in the club. In 2008-2009, Messi won his first Ballon d’Or by helping Barcelona to win 6 trophies in a year, including Champion League. After that unforgettable year, most people started to acknowledge Messi’s skills. After his victory, Messi publicly said ‘’I started early, and I stay late, day after day after day, year after year. It took me 17 years and 114 days to become an over-night success.’’ Messi proves that without his hard work, his talent and success wouldn’t exist. We tend to look at what he has rather than how he achieved it. We only see him when he’s on the top of the mountain, but never noticed him when he was climbing.",
      "‘’If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all.’’ – Michelangelo",
      "Another factor is the environment; it also plays an important role in improving talent. For instance, if children were raised in a singer family, those children will most likely are going to be singers in the future because of what their parents influence them. Children are like papers, they can get stained, cut, and folded pretty easily so, if they see their parents doing something over and over again, they will try to mimic them. Another positive reason is environment can as well sharpen their way of thinking and the way they interact in the real world. Michelangelo was one of the greatest artists of his time, he was born in the Republic of Florence during the High Renaissance. Considered by many the greatest artist of his lifetime, and by some the greatest artist of all time, his artistic versatility was of such a high order that he is often considered a contender for the title of the archetypal Renaissance man, along with his rival, the fellow Florentine and client of the Medici, Leonardo da Vinci. Michelangelo was influenced by many artists throughout his career. Although he preferred to tell people that he was self-taught there were those along the way who helped to shape his skills. For example, at a young age Michelangelo worked under the great Florentine sculptor Domenico Ghirlandaio, who helped to form Michelangelo’s opinions about art, and taught him different drawing methods. Due to the environment that Michelangelo was raised that turned him into a great artist. Environment can also influence our passion. If our passion is painting, then our environment can also be one of the factors that helps us sharpening our passion. Salvador Dali, one of the most famous surrealist painter in the his-tory. Dali was born in Spain, the place where many spectacular and brilliant artworks located in, he also was born during the era that paintings were so popular, so precious for most people. This led him to observe and obsess with painting because of the influence, inspiration, and the impact from his envi-ronment since he was around 6 years old. When he was 12 years old, Dali started to learn how to paint at the drawing school called Colegio de Hermanos-Maristas and the Instituto. Due to the inspiration and influence by famous artists that were in his era, Sal-vador Dali was became so passionate with art, and soon became the famous artist in Spain.",

      "Last factor is passion, it’s certainly true, that most of A, B students are the students who have love study-ing, who take things very serious on their lessons, who always pay attention while learning. While C, D, E students are the students who enjoy doing differ-ent stuffs, such as hanging out, playing video games. This is passion is all about, passion is the factor that motivates us to work hard and give everything we have to what we love. Hard work without passion is like a great hunter without good equipment, when a decent hunter goes hunting without equipment he needs, he might not be able to hunt animals effec-tively like other hunters who have equipment. Simi-lar to the guy who works really hard without passion, he won’t improve his skill effectively like the person who has, because he doesn’t have motivation, inten-tion in doing it. This is why some people spent the large amount of their life practicing but still not fruit-fully improve like others, because they don’t spend all their attention to what they learn. ‘’I have no special talent, but I am just passionately curious’’ –Albert Einstein When we love something, we tend to focus, pay all our attention and do it with strong intention, with love, we take thing seriously without noticing on it, and these actions will cause our skill to improve rapidly and effectively than others. This is why most talented people seems to fall in love with their talent, and this is the reason why they got their talent. If we ask talent painters about how they are so good at painting, they might say ‘’I have been practicing for a long time, and I love painting.’’, and if we ask Messi how he become so good at footballing, he must say ‘’Because I love playing it’’ The famous tennis player named Roger Federer once advised to young players about how to reach their dreams, mentioned ‘’First, you have to have a passion for the game’’ In short, passion is the factor that pushes us to work hard to attain what we aimed, and the factors that push-es us to give everything while we trying to achieve, it’s the inside power. Without passion, there will be no motivation, without motivation there will be no inside power. Yanni Chryssomallis, a famous Greek self-taught pianist, and composer said ‘’All you need is passion. If you have a passion for something, you’ll create the talent.’’",
      "In conclusion, talent is special aptitude that everyone possesses it. Not everyone is already born a scien-tist, doctor, footballer or singer, yet as human beings, we can develop our talents to fit in different catego-ries. In our ideas, we have come up with a cycle of talent: it starts with environment, up to the passion, till hard work and back to environment again. The reason is that we contemplate they are related to each other, if one of them was out of the picture, the other two wouldn’t correlate with each other. Never-theless, as we read the paragraphs above, there are enough evidence to prove that talent wouldn’t exist without doing anything, it’s not a gift from the god that sent to everyone. However, talent is the combi-nation of three factors, hard-work, environment, and passion.",
      "‘’There’s no talent here, this is hard work. This is an obsession. Talent does not exist, we are all equals as human beings, you could be anyone if you put in the time. You will reach the top, and that’s that. I am not talented, I am obsessed.”  - Connor McGregor",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Three smart goals to help you accomplish your ideal life",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956990/InsperU/Top_of_Mountain-01_aqip5w.jpg",
    postDate: {
      month: "May",
      day: "15",
      year: "2018",
    },
    authors: ["Tola Ouk"],
    category: ["life-tip", "personal-development"],
    content: [
      "Commitment here refers to the ability in which I can attach the goal and my determination to reach it even when I face obstacles. I believe that goal and performance are strongest and most effective when we are committed, and even more so, we might think that goals are difficult. I think that in the presence of strong commitment, there will be a significant relationship between goals and performance; I strongly believe that in order to be successful, we must have a strong desire and a comprehensive understanding of what is required to achieve it.",
      "When a goal is too general, it can limit our motivation value which will make us lose interest in attaining the goal that we want to achieve. Therefore, I think that setting a specific goal will put me on a direct course. I plan on setting clear and precise goals that can be measurable with KPI. Key Performance Indicator is really important for me because it lets me see my progress and where I am at which point.",
      "In order to have a stable job, I think that it is absolutely important to make as many connections as possible because when people know you for a long time, they can recommend jobs that are well suited to your ability. I can do that with online social media platforms these days such as Facebook and especially Linkedin which is getting more famous among the new generation. By establishing my own identity and profile, I can now use these tools to help me spread and advertise myself much better and easier.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Globalization is important for any countries in the world",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/GLobalization-01_o6ydke.jpg",
    postDate: {
      month: "April",
      day: "25",
      year: "2020",
    },
    authors: ["Tola Ouk"],
    category: ["social", "economic"],
    content: [
      "Over the last two decades, our society has witnessed unprecedented changes in the overwhelming trend of globalization. From the traditional water festival to the western white Christmas. From the family-centered cultures to the more independent living style. It is undeniable that globalization is slowly taking all over the world bit by bit. However, the influences of globalization are not all bad, because the positive effects of globalization cannot be neglected.",
      "Globalization benefits us in far wider ranges. Ever seen the accelerated development of globalization, mankind is introduced to new tools and technologies including credit cards, medicines, and most importantly the internet, etc. Globalization is not only changing for the better but it is also an opportunity. It is an opportunity to make improvements on our parts, to keep pace with the other developed countries and it is an opportunity to present to the whole world the merit of our culture.",
      "In addition, it seems meaningless whether our traditional value is better or western’s is better. What is important is the selection process. What we should do is absorb the essence and desert the dregs, why do not we consider it as critical assimilation? Imagine if the essence of different cultures and values are collected and combined with that of our own, we cannot only possess the incredible traditional culture that has instructed and inspired hundreds of generations of our own country. But on the quintessence of other cultures some having been cultivated over the long course of history. As for us people of the 21st century, we can see the drastic innovation the society has been undergoing and the current circumstance can bring about rap-id development to the culture of our society if dealt with appropriately.",
      "In conclusion, globalization brings many benefits along with it, from modern technologies to presenting the world of our own culture. Therefore every country needs globalization because it will help us in time turn our culture into a more civilized one.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "The effect of social media to the young consumers",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/Social_Media_and_Teen-01_sv26au.jpg",
    postDate: {
      month: "March",
      day: "10",
      year: "2018",
    },
    authors: ["Meng Huo", "Tola Ouk", "Eakseng Meng"],
    category: ["social", "issue"],
    content: [
      "Business marketing is constantly renewed to create new concepts and strategies every single day. It is in this context that digital marketing has emerged as one of the largest areas of business marketing. Its existence has proven to be very crucial for the growth of the due to the new area of business: to be focused on the producer now directed towards the customer. That has been noticeable in revolution over the last half-century. Besides this, there has been a continuous flow of advanced technology. The possibilities in all parts of knowledge have been increased because of the technological development in Cambodia. It was not difficult to foresee: joining marketing technology and increasing its strength as a tool for marketing. With the advent of the Internet, the rise of e-mail, new media communication, and computing expansion some of the elements are pushed to maximize their potential.",
      "The target of young consumers in Phnom Penh is the easiest to persuade in digital marketing. And the use of social media is an innate part of them. For this reason, the mobile phone has become a vital device entering this industry. Many studies conducted had mentioned that it is increasingly clear that the mobile has a predominant role in the life of buyers. The proportion of users who uses the phone for entertainment purpose has increased three times, in the last decade. Youth in Phnom Penh is the main user of the new media from the development of new technologies and therefore one of the most important objectives of the strategy’s companies advertising in the media.",
      "In Phnom Penh, the youth is segmented from young adults to the so-called Generation Z, which is one of the most in the crosshairs of traders in recent decades. New media is used by this segment primarily for entertainment rather than information. Social media are becoming increasingly important since the 2000s, especially Facebook and Instagram. They also download videos and music, watch videos and TV online, play, and do online shopping. Notably, increased activities relate directly to Facebook.",
      "As a result of this, companies have had to adapt their advertising communication to this segment in several respects. By using social media as a platform for digital marketing; there can be a reduction in the expense of traditional advertisement. Moreover, it can help build brand awareness; digital marketing can significantly increase traffic to a site to generate more customers. Therefore, social media is undoubtedly one of the best channels for digital marketing.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "The un-talk culture of salary",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/Money-01_a5q2jh.jpg",
    postDate: {
      month: "March",
      day: "18",
      year: "2021",
    },
    authors: ["Chirika Phang Lee"],
    category: ["job", "social", "personal-story"],
    content: [
      "I got the shocked of my life when Igot my first intern job last years, that you don’t discussabout your sala-ryor your co-worker salary with each other,nomatter how close you are with them. It’s like a culture or a rule. It’s like it wrong to find out that you might make more or less than your co-worker. Peoplewon’t tell you it bad or offensiveto askabout it,they will glareat you, like you break some rule that you shouldknow. The reason Iask other co-worker about their salary is to know how much they made when they got the same job and join to work as the same time as me. Is this person pay more than me why, what this per-son have or do to germore pay, or why is this person getpay less than me.And alsoIwantto know is there a pay gap as the same at foreigncountieswhere men are being paid more than woman. But Iwill nev-er know about that now.Irealize that adult that are workingfor 3 to 5 years now that they don’tshare how much they make to their close friends. When ask “why?”they replythat it weirdto take about, andwhat happenedtheymake less it embarrassed!Ialsostart tobelievepeopledoesn’t want to share about how much they got paid is becausethey afraidthat other will start to ask for something from them and treat them differently and when they brokeor aren’t willing to helppeople will turnon them. Well Ibelieve people should talk and share about their payment, so fresh graduatecan preparethemselves for what to come and because you might not know thatsomeone or maybe even you are being taking advantage.",
    ],
    likes: [],
    comments: [],
  },

  {
    id: uuidv4(),
    title:
      "Are cultural dimensions mentioned in the book practically accurate?",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/Japan_Culture-01_fwavln.jpg",
    postDate: {
      month: "June",
      day: "05",
      year: "2021",
    },
    authors: ["Meng Huo"],
    category: ["culture", "social"],
    content: [
      `Well, I agree with Erin for the most part, however, I believe that it leads to "stereotypes". I remember when I was discussing with my German friend, Mitchel (I probably spelled his name wrong), he mentioned that as a German, there are many stereo-types about his culture which are inaccurately stat-ed. For instance, he wasn't that serious (German is a stereotype as serious/strict), he made jokes, is playful, and is a very open person. This tells me that I can’t just depend on this cultural theory I learn because it depends on the person individually. With respect, I am not saying what Erin wrote is misleading, but rather it is overused to the point where it becomes inaccurate. Anyway, this book has so many great insights that catch my attention. Besides, most of the main ideas in the book are easy to understand since it is mostly discussed in the lecture. And, here are the top 5 insights /quotes for me; "Kuuki Yomenai", "How to feedback", "Working in the group", "Guanxi", and "How late is late".`,
      "First of all, the Japanese phrase, “Kuuki Yomenai”, means can’t or unable to read the air. It caught my attention the first time I read it because I could re-call back during the Japanese guest speaker. I believe she mentioned that same phrase, which she mentioned that environment/surrounding plays an important role in the conversation with high context culture. I agree with the author about this idea, but I noticed that the book considered most European countries as low context, which I have experienced otherwise. During my fall semester in Lithuania, many of my European friends did know how to read air. For example, when we were discussing our countries, Alexander (Lithuanian) always compliment Cambodia whenever I sound excited over my statement. I think he read my tone of voice and facial expression. So, to me, saying that low context culture can’t read air is not entirely true, but in most cases it is true.",
      "Second, how to give feedback. With all the technologies, globalization has become more common; working in an international group happens quite often. Erin mentioned that in this kind of situation, feedback is very important. She explained that some cultures prefer direct feedback, while some cultures don’t like being confronted, thus preferring indirect feedback. I agree with the author in this aspect because I have seen both types of cultures. From my experience, German would take any form of feedback without getting offended. When I work with them, they would constantly ask me, “what do you think?” On the other hand, when I give an idea they would feedback immediately. If they liked the idea, they said “smart”, if not, they said, “how about this…?” Spanish is on the opposite side; my Spanish friend would always say “perfect” to any of my ideas. I don’t know if that is true for all Spanish but that is definitely how I experience Spain culture. Moreover, when I work with Ukrainians, they would work quickly and finish as soon as possible. Then, the feedback part would come after everything was finished. The way they do it, they vote to keep it (if it is good) and vote to remove it (if it is bad). Overall, Erin is right, for me (indirect culture), I sometimes feel down cause of how others give feedback, but after a while, I adjusted and worked with them smoothly.",
      "The third aspect is working in a group. The author divides the leading system in a group into 2 different styles, Egalitarian and Hierarchical culture. Based on my understanding, I think Cambodia is probably a hierarchical culture. So, whenever I work in a group, I expect my team to have a leader. However, it wasn’t the case when I did my assignment during my exchange semester. All the teams I worked with don’t care about who was the leader. I thought it is impossible to work without someone to lead, but it was quite better without a leader in some circumstances. By working closely together with everyone having equal power, the workflow goes smoothly. I am not saying that hierarchical is bad, but I would prefer Egalitarian overall. Ultimately, it is not about which is better but rather understanding both concepts to avoid making mistakes unintentionally.",
      "Fourth, is the Guanxi effect. The author stated this Chinese word to explain how trust works in China. The reason I am interested in this concept is that I have experienced this before. The first time I met my Chinese friend, Joe, he was even more serious than the German gentlemen. But after some time, he started to be more open and talkative. This might also fall into the definition of coconut culture. I remembered one-time Joe even said, “Chinese doesn’t make a joke.” I and other friends were like “What??” So, he explained that they only joke around close friends or family, unless there is a lot of trust in the relationship, the Chinese tend to be holding back.",
      "Lastly, the time concept of culture. In the book, there are 2 main concepts: Linear time and flexible time. I thought it is interesting because not only do different countries have different time rules, there is an influence between them. Meaning that after some time one culture can change another culture. To elaborate, I had a few trips with the exchange students’ group, which includes many nations such as Cambodian, Chinese, German, Georgian, French, Belgian, Spanish, Malaysia, and American. Out of all, the 2 Spanish guys always appear last on any trip. They are always 15-30 minutes behind others. I don’t mind that because it happens every day in Cambodia. But what is interesting here, after a few trips I noticed that the German guy also appears late with the Spanish guy. Hence, it is clear that a person of one culture can influence another person of a different culture to follow.",
      "To sum up, I wish I had read this book before my exchange program because I would have adjusted better and made fewer mistakes. Though it is not the end of the world to commit cultural mistakes, it is the best way to learn a culture, in my opinion. All information in this book is absolutely helpful for anyone as it is easy to understand and relatable. There are many more cultural aspects that are yet to be explored. I would say let’s go out there and talk with other cultures and find it out.",
    ],
    likes: [],
    comments: [],
  },

  {
    id: uuidv4(),
    title: "Human communications are more revealed in body language",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/2-01_rh1npn.jpg",
    postDate: {
      month: "July",
      day: "27",
      year: "2021",
    },
    authors: ["Leangheng Ou"],
    category: ["psychology", "social"],
    content: [
      "When we are unhappy with someone during the conversation we would pretend that everything is okay and hide our true feeling by muting statements that we wish we could let out. In most conversations, we try to be nice as we possibly could. Giving positive feedback, avoiding making judgments, and more. During difficult conversations with our co-workers or business partner, we don’t want to let the anger out cause it could potentially sabotage the relationship.",
      "Yet, there are still some parts of us that we are not in control of all the time. Our body keeps sending signs even when we try to lie. Our tone of voice could turn aggressive when we are mad, and soft when we felt weak. These reactions on some occasions are hard to respond to so hide them away. Because the body muscle needs its way to relieve the tension.",
      "For example, a woman suddenly uses an aggressive tone of voice while saying polite words during the conflict. Another example is a man always touching his ear when being asked if he stole something or did some crime. Mostly, when a person always touching their ear or neck it’s a sign showing they are nervous and trying to hide something.",
      "Words are tools to lie and deceive people. It is used to manipulate others to serve our interests. A person could say anything we want in an instant.  That is why we should pay more attention to body language, facial expression, and tone of voice instead of putting our trust in the words people say.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "The impact of industrial revolution",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/Robot-01_lusvlp.jpg",
    postDate: {
      month: "June",
      day: "13",
      year: "2019",
    },
    authors: ["Tola Ouk"],
    category: ["technology", "economic"],
    content: [
      "As the world is shaping itself rapidly every single day, so is industry. Mankind is being led to a more sophisticated life. The first industrial revolution started in the 1760s and it has altered the way people work as well as the entire productions themselves in any industry. Industry 4.0 is about connectivity, it is an opportunity to radically shape the way industry responds to the needs of society. In this essay, we will examine the impacts of industry 4.0 in 2 main areas which are economic and environmental.",
      "To begin with, the introduction of industry 4.0, helps a lot in the economic sector mainly the decreasing cost of production. Companies nowadays are seeking many opportunities from three-dimensional printing. Those companies have just begun to adopt additive manufacturing, such as 3-D printing. These 3D printing machines can be used in so many different ways but mostly, for prototyping and producing individual components. With industry 4.0, these types of technology are getting cheaper and more affordable because of the higher demand from the market, especially in the field of innovation and entrepreneurship. According to an online article, it mentioned that companies such as aerospace are already using additive manufacturing to apply to new designs (Lorenz, 2015, para. 9). This approach could reduce the aircraft weight, lowering their expenses for raw materials such as titanium. This new technology will be very helpful in economic growth as well mainly in reducing transport distances and stock on hand.",
      "Secondly, corporate social responsibility (CSR) has been an important part of any company these days because it is a way for companies to show off their activities and what they have done for society to the public. Moreover, based on an online article from the University of Applied Sciences, predicted that companies can implement more efficient energy management (Gabriel & Pessl, 2016, p. 141). The new industry 4.0 facilitates greater transparency in the energy system of a company. “ Smart grids’’ help the company to better understand how their energy consumption is being used and whether it is effective and efficient enough (Castagna, 2019, para. 1) This can reduce energy costs and extend the life cycle of the user devices (Jasperneite/Bretschneider 2013). In addition to saving the environment, transportation also plays an important part since we are living in a globalized world where people buy so many cars in which this activity affects releases carbon dioxide into the air which damages the earth. Now, with industry 4.0, everywhere can be easily accessed in a short time and convenience. More people are starting to realize that they do not have to buy a car anymore to travel to work or anywhere. According to economic-forum.com, as traffic congestion continues to grow more and more in urban areas, more citizens have realized that the government should invest more money in public transport modes, such as metro trains, bus rapid transit systems (BRT) or buses, instead of personal vehicles (Fang, 2015, para. 1).",
      "In conclusion, the industrial revolution will bring about major changes to the world we live in today. It will not only make the lives of the citizens more convenient and accessible but also contribute to the environment as well. From steam-powered to the mass production model that dominated the second, or even the emergence of computer-driven systems from the third revolution that we are living in today. This new industry 4.0 will help shape the world into a ‘’gig economy’’ where people can work from home or anywhere they want to without having to travel far.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "The feeding frenzy",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/Frozen_Feeding-01_dww1nr.jpg",
    postDate: {
      month: "October",
      day: "02",
      year: "2017",
    },
    authors: ["Alyssa-Jayne Tain"],
    category: ["social", "issue"],
    content: [
      "Over the past three decades, obesity-related health problems, such as coronary heart disease, cancer, and type 2 diabetes, have been continuously rising. These health problems are clearly all related to food consumption, meaning that our current society has a major dieting issue. Such, Feeding Frenzy discusses the huge role that food industries play in making up our society’s overall health. In fact, despite the media’s constant focus on how obesity is a personal failure and that with the right diet and the right amount of effort, it can be overcome, 1/3 of Americans are obese. Therefore, this isn’t about an individual’s willpower to change, this is about how obesity has become a societal problem, mainly due to marketing from the food industry. The documentary showcases how our capitalistic society has led to food industries being money-driven and, such, causing major health crises. The food section has largely been able to achieve its goals through its diverse marketing strategies. For example, many companies try to associate their foods with the most important moments in people’s lives (Coca-Cola advertisement). Supermarkets are also always arranged in long hallways filled with products and escape routes, obliging customers to walk through the whole hallway, which increases the chances of bigger purchases. Furthermore, processed foods are usually genetically modified and contain a lot of chemicals. They are also sold at a much cheaper price than foods that do not contain as many chemicals. , because there is so much distance, mentally and physically, between these processed foods and the consumers, customers just end up choosing the cheaper options, which encourages industries to sell more cheap processed foods. In other words, the food industry is willing to do whatever it takes to get clients even at the cost of a whole population’s health.",
      "Such, I do think that the documentary is right blaming our current society’s obesity-related problems on the food industry. This has indeed become a societal problem when 1 out of 3 Americans are obese. I believe that it is important to also let others know that this isn’t just about personal responsibility. An individual shouldn’t be entirely disappointed by their weak willpower, as this is the actually-major problem caused by our money-hungry society. What’s as scary as our growing health problems is the food industry’s marketing system. The fact that food industries would do anything to get customers is honestly very disturbing. For example, many companies create, for the customers, an illusion of health by creating green-colored labels, inserting words such as “natural” and “whole wheat” onto their cover, and inferring health claims. Moreover, most advertisements are targeted toward children, as they have large spending power and purchasing influence. As well, children could be conditioned to become loyal consumers. Additionally, the products that are constantly being sold and marketed are incredibly bad for the consumers’ health. These products contain huge amounts of sugar and, consequently, make self-control very difficult to achieve. For example, Doritos are made so that you can’t just have one bite. Even educated people on this matter have a hard time avoiding junk food. Portion sizes have also grown, making self-control even more difficult.",
      "I do find scary the degree to which companies are willing to take to get people to purchase their products. Regrettably, I think that the only way to solve this is to completely change our political system into one less axed upon maximum profit.",
    ],
    likes: [],
    comments: [],
  },

  {
    id: uuidv4(),
    title: "The three habits of creative people",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/Creative_People_tshhfc.jpg",
    postDate: {
      month: "March",
      day: "01",
      year: "2019",
    },
    authors: ["Leangheng Ou", "Seihakpiseth Tan"],
    category: ["personal-development", "life-tip"],
    content: [
      "Creativity is a powerful weapon used by all living things, not only us, humans, but animals too. To simplify this, creativity is the act of making or in-novate something new based on ideas. Most of us consider artists or writers are highly creative people. However, creative ideas can just pop up out of nowhere, and sometimes we don’t even realize it. Creative people tend to have unique habits that made their minds into thinking more creatively. The question has risen what are those habits? And what can we do if we want to be like them? Based on our observation in the past, we’ve found that everyone can be creative, and everyone can be like anyone. We’ve found that creative people tend to have three different habits that most people don’t. There are thinking beyond their limitation, think differently from others, and are willing to show their ideas to the whole world without any hesitation.",
      "Firstly, creative people tend to think about something that doesn’t exist yet. They aren’t interested in doing what the world has already done, but they like doing something that the world hasn’t done yet. As we can see, when we look at creative things such as television, smartphones, computers, cars, cameras, or light bulbs, those are the things that people 1000 years ago couldn’t imagine and would never dream about. The fact is, that kind of stuff is always found by the people who have unimaginable ideas. For example, Steve Jobs was one of the most influential people in the world. Steve Jobs was the man that tried to do something that people in his time couldn’t believe, something that changed the world. He was the founder of a computer called Macintosh, it was the first computer that ever made included a mouse which makes it easy and comfortable for most people to use the computer. He also invented the first touch screen or called the smartphone. His ideas and invention have impacted the world a lot, such as the way we work, study, and communicate with others. Because of his unbelievable ideas, Steve became so successful and was recognized as one of the most creative people in the world. And of course, there are a lot more creative people like Steve Jobs such as Nikola Tesla, and Thomas Edison that invented unimaginable things in history. Neville Goddard, the famous spiritual philosopher of the 20th century once said ‘’There is no limit to your creative power’’. It is true that creativity no has a limit. Inside the mind of creative people, they always think that stuff we already intended has a limit, but the stuff that hasn’t been intended for us has no limit. This is why they like to think and do something that most people can’t believe, something that is beyond the limitations of others' imagination. And, we think it right to say creative people don’t like to follow the world, but they like the world to follow them.",
      "Secondly, if you also do the same old thing, and follow the same old path, you are not creative at all. Creative people are prone to think differently from others. They sometimes are the biggest enemies of the same old paths. An American journalist Bill Moyers said ‘’Creativity is piercing the mundane to find the marvelous.’’ Creative people like to change ordinary things to another level. If the current path is simple, they’ll try to change it to match their uniqueness, If the current path is boring, they’ll try to change it to be interesting, if the path is difficult, they will strive to make it easier. Therefore, this kind of habit leads and inspires those creative people to often come up with new ideas in their workplaces. However, inside most normal people’s minds, they always say ‘’Let's do this way, this is the safe way’’ or ‘’Just follow what he/she said because he/she has done it safely’’, or ‘’ We have to do this way, this is the only way.’’ Creative people, always think differently from them. Creative people are willing to take risks when doing things differently from others. The sentence that creative people usually use is, ‘’I think we also have another way.’’ Miyamoto Musashi, the Japanese philosopher stated ‘’ There is more than one path to the top of the mountain.” There is no limitation inside the mind of creative people, and there is always more than one way. All in all, the habit of enduring in thinking differently from others will always influence us to find different ideas from the existing ideas and soon known as new ideas.",
      "Thirdly, they are the type to show how confident they are when it comes to idea sharing.  However, most creative people’s mindsets tend to not involve in the crowd that much because unnecessarily conversations are not for them. Nevertheless, being an introvert person or extrovert person doesn’t mean you’re creative. According to research, our DNA is probably most responsible for being creative or not.  if some creative people are introverts, we can’t consider them rude or mean people just because they don’t socialize as extroverts do. Nonetheless, when it comes to ideas, they are always open up and always trying to learn new things. Additionally, having those creative people in a team will make the discussion even better.  Elanor Roosevelt said, “Great minds discuss ideas; average minds discuss events; small minds discuss people.” For example, Mark Zuckerberg, is an American technology entrepreneur, philanthropist as well as the founder of Facebook. He is one of the most creative people based on his creation, Facebook. Another example is Steve Jobs, Jobs was the founder of Apple, and he also shared his idea through inventions and Apple products. He wasn’t the type to let his body wander around, just his mind that was wandering around, That’s why he came up with Apple.",
      "In conclusion, every one of us has our uniqueness as well as our creativity. Being an intelligent individual doesn’t mean you have a creative mind. On the hand, being a creative person doesn’t mean you are smart, it means you are more governed in the way you are thinking. Those three habits that we have mentioned above are established by our experiences and points of view, there are more ways to be creative. Like Albert Einstein once said,” Creativity is contagious, pass it on”.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Livingin city and staying in small village",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/City_vv_h9xhgl.jpg",
    postDate: {
      month: "february",
      day: "11",
      year: "2019",
    },
    authors: [
      "Lim Vouchleang",
      "Karn Sreypin",
      "Ouk Tola",
      "Sarboeun Sathyamonyrak",
    ],
    category: ["lifestyle", "social", "personal-story"],
    content: [
      "Some people always prefer to live in a big city while others prefer to live in a small town. Everyone has their point of view, different thinking, and reasons to choose where to live. The three deciding factors for their preference depending on the environment, employment, and technology.",
      "First of all, one difference is the environment. In a big city, population growth is increasing dramatically every day. Many industries and factories are needed to fulfill the need of the citizens. This is the core reason why pollution is a big issue that people living in town. However, there are very least even factories located in the countryside. This leads to a fresher and better environment in the village.",
      "Another difference between living in the city and small village is employment. People who live in the city find it easier to find jobs because of the wide variety of opportunities and different fields in the workplace. Conversely, due to the slow improvement and the lack of human resources, a lot of villagers can barely get a well-paid job to make enough income to support their families.",
      "Last but not least, technology plays an important role in considering whether to live in the city or a rural area. With the fast growth of technology and facilities in most cities, people can easily live their lives with convenience. Moreover, the modern transport stations that the city offers, make working and living even more accessible. In contrast, electricity is often very poor and distant for people who live in the far urban area; thus people usually use the old traditional ways of working and living.",
      "In conclusion, both city and small town have their advantages and disadvantages. Everyone has different thoughts in choosing a place for living a life. It ultimately depends on the taste of people.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Cliques and their impacts on students",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/City_vv_h9xhgl.jpg",
    postDate: {
      month: "May",
      day: "15",
      year: "2019",
    },
    authors: [
      "Nguon Sokheng",
      "Sophean Chantrea",
      "Lim Leaksmey",
      "Ly Muy Eng",
      "Nov Sotharyna",
    ],
    category: ["social", "issue"],
    content: [
      "In a diverse world of many people coming together, nobody can live without social interactions.  From birth, we are welcomed by a particular group, to which we feel closely connected.  As our circles grow, we are exposed to various types of people, but we only tend to prefer to interact with the ones who are like-minded to us. Little by little, this kind of mindset becomes stronger and stronger to the point that we no longer feel the necessity in communicating with other people. As a consequence, the term clique was coined to describe a small group of people who spend their time together and do not welcome other people into the group. A relationship like this can be seen mostly among students because they are at an easy stage of being influenced by their surroundings, and they have a strong need to feel accepted and belonged. Whether voluntarily or involuntarily, we all get involved in some kind of cliques, and we, ourselves, as students can witness the presence of cliques in our classroom. Because of its noticeable impacts on the students both inside and outside the clique, we have decided to choose this matter as our main topic to conduct an attentive study on. In this paper, we will discuss the benefits, drawbacks, and related theories to cliques.",
      "Clique plays an important role in contributing not only to students’ in-class but also their out-class performance. The formation of cliques can be identified within different social environments and many significant factors throughout their lives, such as race, gender, religion, social status, social class, shared interests, and so on.  As expected, clique comes with both positive and negative effects; having a favorable group is essential for social upgrading, meaning that students can pursue and develop themselves by using the positive traits of other members in their clique as a reference group. Most importantly, it provides a sense of belonging, which can help them to figure out who they are and boost their self-confidence in trying new things, as they know that they are not alone. For instance, if one belongs to a group that is interested in studying, that individual will tend to imitate and conform to the habit of studying as well to be a part of that particular group. In addition to this, people in cliques are also free to express who they are, as they feel comfortable, warm, and without fear of being judged. However, in most cases, the disadvantages of cliques hold more power and effects than their benefits. Cliques can tear apart a lot of things in a matter of seconds, and this does not only happen to people outside the clique but to the insiders as well. For clique is seen as a brutal barrier to the outsiders as the whole group is not willing to accept others in. Because of this, students who do not belong in any cliques will feel lonely, and unwanted and find it hard to fit in. This is the main reason that leads to discrimination, which will create in-groups and out-groups. People tend to view the trait of their in-group as goodness, while the same trait is viewed as wrongness in the out-group. Besides this, the negative impacts of cliques do not only fall upon the outsiders but the insiders as well. Being in a certain type of clique sometimes takes away the chance from the students to be comfortable in their skin because they are afraid that they might no longer be able to stay in their clique. Furthermore, cliques rarely allow us to let new people join; as a result, this will affect your ability to change yourself and learn new things. Also, your communication skills will worsen. These are all the big issues that come alongside cliques.",
      "According to the functionalist perspective - which sees all parts of society working together to accomplish social harmony and social stability, clique is viewed as a prominent component that instructs individuals on how to work collaboratively and effectively in a society. Based on the same theory, cliques serve as a bridge to unite compatible people who can support one another and pursue activities that the members will all enjoy, which sometimes can contribute to social stability while sometimes can be disruptive to society. With the existence of cliques, people are also more likely to think alike and have the same perceptions toward their surroundings, and this is what leads to group-think. From the perspective of a functionalist, group-think allows the members belonging to the same clique to work together more effectively and more efficiently as everyone has the same goals. Conflict theorists, in contrast, believe that people at school are all different in various qualities such as attractiveness, fitness, and access to physical resources; hence, they fall into different areas of the spectrum of acceptability. Thus, the “superior” members of the school environment get together and oppress the “lesser” ones.",
      "To gain a better understanding of the topic above, our group has conducted a small and simple survey to our targeted audience who are students. We conducted this survey to enhance our level of understanding to a better degree of the topic at hand. Our group of six individuals slowly and deliberately formulated a questionnaire related to cliques and asked our chosen participants to give their honest opinions and perspectives on the formation of cliques whether they think of it as a good or bad thing. We have created nine questions that are complex yet simple enough for the average audience to understand. The questions that are included consist of opinion-based, multiple-choice questions that are based on general knowledge and our very own understanding. According to the results from this survey, eight out of ten people believe that everyone at school is in a particular clique. On the other hand, the remaining two agree with the idea that people can become friends with anyone and everyone, even if they are different from them. Based on the data, ten out of ten people think that cliques exist because people want to achieve a feeling of comfort, trust, and loyalty. Additionally, four candidates also state that another factor that leads to the form of cliques is avoiding isolation.  Moving on to another part, seven out of ten participants view that cliques can be both positive and negative, while the other three only see the dark side of cliques.",
      "Through our knowledge and the results from the conducted survey on the topic, it can be concluded that cliques can be both good and bad, and even though their drawbacks outweigh their benefits, sometimes it depends on us, ourselves to let how much of an impact clique has on our behaviors and perspectives toward in-class performance and classroom interactions.",
      "The world of cliques is very complicated and confusing. By being in one, students can be at an advantage or at risk of improving or disimproving themselves. Looking at it from a positive side, cliques give students a sense of belonging, confidence, and the potential to discover where they belong. However, from the opposite side, cliques can be hazardous as they limit creativity and diversity in friendships. It can be very difficult to not fall under a student clique but to avoid all those negative impacts, you have to be an open-minded person by trying to respect and understand other people; if every student practices this, the drawbacks of clique won’t be the most serious problem that affects their performance inside and also outside the classroom.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Amusing ourselves to death response paper",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1661120405/InsperU/Amusing_Ourselves_to_Death_Respone-01-01_xvets4.jpg",
    postDate: {
      month: "June",
      day: "23",
      year: "2020",
    },
    authors: ["Meng Huo"],
    category: ["social", "psychology"],
    content: [
      "Inspired by “the medium is the message” (McLuhan, 1967), Neil Postman used the phrase as his fundamental point and developed a new media theory in the age of television. In his experiment, television was the focus. He analyzed media evolution throughout the history of America and pointed out that media has a major impact on society’s literacy rate. In his finding, Postman believed that medium does not only affect the way a message is received but also shaped the discussion among people in society. This paper will discuss Postman’s three main ideas, including “the medium is the metaphor”, “Peek-a-Boo world” and “teaching as an amusing activity”.",
      "First, “the medium is the metaphor”, argued that medium had an impact on how information is retrieved and at the same time limited the topic that should be addressed from the message itself. Postman believed that a medium is more than a message but rather a much more complicated metaphor. Television, for example, framed audiences to examine messages from a different perspective. It also slowly shaped the discourse, that we communicated daily. The problem is that society stopped discussing some big topics, like politics, education, religion, etc. According to Kövecses (2018), the medium did affect our discourse by creating virtual realities. These virtual realities could cause us to feel offended, fun, manipulate, lie, etc. It can be found in advertisements to increase sales. In the long term, people are manipulated by unnecessary information. Kövecses concluded that there should be ethical responsibility for the medium, but that depends on how much influence advertisements had put on the medium. While, as an individual, learning about metaphor theory could greatly help us.",
      "Second, the “peek-a-boo world”, claimed that the media was playing kid games with audiences. In the nineteenth century, media was written-based and challenging to receivers. Readers must use logic to analyze the data. Thus, the literacy rate was high and people were informed about their society. Then, the medium developed into visual-based with sudden access to information. Television, for instance, gathered data around the world quickly and broadcasted it to millions of audiences. The complication is that the news was getting overwhelm. There was no coherence or sense in information for the audience to be informed and rational. It just went on and on without caring what the public thought. The audience hadn’t any chance to share opinions with that news at all. It was like a peek-a-boo game for the baby; it provided endless enjoyment but the baby didn’t learn anything besides being joyful. Television manipulated people into that having a glimpse of an event is enough to be informed. Postman regarded that media were competing for quantity over quality, which could heavily affect people’s perception. William H. F stated “by the end of the nineteenth century, advertisers and newspapers had discovered that a picture is not just worth a thousand words, where sales were concerned was better” (William, 1834). This was exactly how television saw it. It used photographs and overwhelming information to hook people into endless entertainment and increase sales. People prioritized short-term fun over politics or economics.",
      "The third idea, “teaching as an amusing activity”, explained that everything had turned into entertainment. Television became the new learning place for children. People considered by adding entertainment into education, kids will like learning. Unfortunately, it only made the kids love television, not the book. Postman worried that people start to look at everything entertainingly. Whereas television was not a literate and logical platform, the knowledge that we learned from there was not credible. This practice led to irrational thought and ignorance of big issues in culture. Also, the information could be misleading and create confusion, especially in politics. According to the journal Reilly (2011), Canada experienced a media election in 2011. Candi-dates used social media as a platform to promote and don their campaign. They targeted youths, aged between 18-24, considering these youngsters didn’t know much about politics from their media. Politicians used YouTube videos, editing, elegant color logo, and manipulated picture. Thus, people voted for the most attractive campaign, not the one with the best vision and principle.",
      "In conclusion, Postman was right about the medium. It is not just affecting the message itself, but also indirectly shaping the culture. His theory is a great way to look at how media impacts a civilization. It is slowly shaping the culture differently. This can be problematic if people continue to ignore what the media does. However, it can be great if people start to be aware and use media the right way. In Postman's view, people should control the media, not be controlled by media.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Fear of the unknown",
    postDate: {
      month: "March",
      day: "23",
      year: "2021",
    },
    authors: ["Phang Lee Khemrinn"],
    category: ["social", "job", "personal-story"],
    content: [
      "For when I am trying to apply for some sort of job for the first time, since all I ever did in my past 20 years of experience in life here in Cambodia is holing myself in the room of my parent’s house wasting away, and all I did was go back and forth from school, the thought process of applying for an Intern, or doing it, really frightens me, the anxiety of failing to hear back an email from an Intern I applied, or doing an Online Interview, or even the thought of succeeding in getting the job, the thought of having to show up and do your work, being a responsible individual, hoping when you go to this new place, people will be nice, you would have co-worker or friends to talk with, the job itself, hoping that it wouldn’t be so boring as many of your friends has so far complained about. I don’t have a means of transportation by myself, I have to rely on Grab, for two rides per day, back and forth for a month, would probably estimate 50$, a hefty cost for someone like me when you never got a chance into driving a motorcycle while your brain is developing, now fearing to get on the road when the developing world streets are as dangerous as ever since not quite everyone drives nicely say Japan2 would’ve been beginner-friendly, especially when you have an experience of a bus coming right at you when you were biking across a four road intersect trying to cross a green light while theirs was red. Aside from that, here in 2020, in this coronavirus pandemic, you have to also be concerned whether or not your job will get you involved in a high risk of covid exposure, I mean, you don’t want to get infected or infect your family members for some Intern, yet not trying to Intern now would be a loss of time and opportunity, not the year to be graduating into. But even so, after accounting for all these issues and weighing the pros and cons, after talking to my family members, they encourage me to go out there still, which is a very helpful emotional support. In the end, I ended up, day by day, step by step, taking action towards and applying and submitting my CV anyway.",
      "This isn’t the year for upcoming graduates to be entering the job market and exploring the opportunities in the capitalist’s world, lots of success bread more anxiety and FOMO3 in us all, it can be crippling for some people, to the point of becoming a degenerate who fears going out and socialize, 4 but even so, I do hope some would encourage others, and some themselves would try to experience the outer world as they are bad, but just as beautiful.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Impact of air pollution",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/Air_Pollution-01_lx7twf.jpg",
    postDate: {
      month: "July",
      day: "12",
      year: "2018",
    },
    authors: ["Tola Ouk"],
    category: ["issue", "economic"],
    content: [
      "Every day, human actions have a significant impact on the environment. Through our actions, we are destroying habitats and endangering the lives of future generations. Nowadays, with the accelerated development of human civilization, we, mankind are introduced to new equipment and technology, resulting in a more sophisticated lifestyle. However, with more than 7.53 billion people on the planet, the earth will one day no longer withstand the drawbacks and pollution that humans have left behind. Moreover, with the unstoppable population growth of population day by day,  more trees have been cut down to make spaces and accommodation for the new generation. In addition, more population, also means more transportation needed, leaving an environmental footprint. According to an online news article in, Washington Post, developing countries are found to be more affected by pollution such as air pollution while developed countries are more healthy (Mooney, 2016). In this essay, we will discuss the comparison between the two countries which are Cambodia, a developing country, and Singapore, a developed country in three main areas related to their cases, effects, and solutions.",
      "Air pollution originated from the combustions in the transport, household, industrial, and energy sectors. Burning fuels releases air pollutants into the environment or atmosphere which dramatically affects the quality of air. According to Environment Performance Index, Cambodia, although it is not a developed and industrialized country, still ranked 164 out of 180 countries in 2018. In Cambodia, the transportation sector has the most serious effect on the quality of air as the number of vehicles and fuel consumption is increasing significantly. As reported by The Phnom Penh Post, in 2014, there were more than 3.2 million vehicles registered. Due to this enormous number of vehicles, it will produce a large amount of combustion which extremely pollutes the atmosphere. In this part, if we talk about the symbolic interactionism perspective, it means that people nowadays are addicted to a new culture that shows off their values and property. The riches, therefore, bought new cars to illustrate their property, and the people who live in the medium class attempt to buy new vehicles to not be looked down on as poor or lacking money by the surrounding people. Furthermore, hundreds of tuk-tuks and buses perpetually operating around the Angkor Wat area. The environment in Angkor Wat, and Siem Reap was at risk of damage from acid rain due to the great amount of fuel consumption. From a structural-functionalist perspective, it means that the results had been changing dramatically because of the needs of humans that they are trying to find a job in which income is acceptable and possible to support their families such as those who are driving tuk-tuks.",
      "Currently, many investors came to Cambodia to start their businesses due to cheap labor. Most of the investors are doing business with a factory that takes advantage of cheap labor to manufacture their products in Cambodia. As we can see that factories produce a very serious amount of combustion which extremely threatened the environment. Talking to conflict theory, the worker was exploited by the capitalists or investors and those workers had no choice but to work for those capitalists although they know that they are being exploited. If we reflex this on the environmental issues, because of the advantages that the investor wants to grasp, the atmosphere in Cambodia is indirectly polluted by their factory. As a result due to the diverse issues of air pollution mentioned above, the polluted air can harm the health of humans. It includes discomfort such as irritation to the human’s nose, throat, eyes, and skin. Moreover, it can also cause headaches, dizziness, and nausea. Besides, bad smells made by factories are also considered to be a factor that can harm human health as well even though the odors are less serious.",
      "Singapore is well known as one of the cleanest countries in the world. Trees are grown everywhere and according to research, it is estimated that there are approximately 7 million trees along the street as well as in the park. Moreover, every park is connected to a smart system that creates a clean green society. However, those trees cannot fully keep the air clean which leads Singapore to be faced with air pollution. Singapore first faces air pollution in 1984 due to the dramatic increase in pig farming. Pig farming seems to only affect both land and water pollution but the wastes and the feces that are left from the pig also harm air pollution since these liters potentially contain harmful substances like nitrate, phosphorus as well as bacteria. Because of these substances, many people’s respiratory systems are damaged which causes possible diseases such as heart and lung disease. As a result, this problem is completely solved by the Singapore government by reducing the farm from 200 pig farms which contain about 50000 pigs to 22 pig farms which contain only approximately 300000 pigs by 1990. Similarly, Singapore today still faces air pollution and the main source is not pig farming but the burning of fossil fuels for heat generation in industries, electricity generation, and transportation to meet citizen demand. As a result, those factories emit tons of smoke which creates a haze that affects Singapore’s air quality. Not only this, but this polluted haze also causes shortness of breath, asthma, respiratory irritation, and infections, and can even do permanent damage to lung tissue, which reduces their ability to absorb oxygen even during normal breathing. To minimize this polluted haze, Singapore’s government employs a strategy of encouraging citizens to use environmentally public transportation and electric vehicles. Moreover, reducing traffic congestion is also introduced to improve air quality in Singapore. Artificial intelligence and street cameras should be operated to ensure a smoother flow of traffic. These strategies can ensure that air quality remains good despite Singapore’s dense urban landscape and large industrial base.",
      "In comparison between the air pollution in Cambodia and Singapore, there are some interesting similarities and differences. Cambodia has is a less serious problem with air pollution since there was war and there were fewer factories than in Singapore. In the past, Singapore's air pollution was caused by pig farming, while Cambodia has not encountered serious air pollution yet. But later on, materialism took over Cambodian people's mindset which led to the usage of vehicles to show off their wealth and their power in the urbanizing society. The use of fossil fuels is a big factor in the pollution in both countries. Fossil fuel was the main power resource in the factories for industrial production. Both pollutions in these two countries have such a big impact on the health of living species in their respective country. For the solution to air pollution in Singapore, the government has two solid solutions such as encouraging Singaporeans to use public transportation that cuts down the high rates of traffic congestion and decreases the smoke coming out from vehicles. Adding an AI camera to the roads is also a good addition to the solution. Another solution is to reduce the use of fossil fuel as a power resource and replace it with electricity. Meanwhile, in Cambodia, the only solution from the government is using public transportation but it is not quite convenient because people still value materialism and continue to increase the number of vehicles in the country.",
      "In conclusion, for the past ten years, climate change has been a major and global problem that cannot be neglected and the increase of carbon dioxide is rapidly growing. Some of the highly suggested solutions are to reduce the use of private vehicles and more public transportation such as public buses and metro for a faster commuting experience. Furthermore, we can also conclude that the government alone cannot tackle all of these problems at once without the help of all citizens too.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title:
      "The production of genetically modified crops has been increasing around the globe",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/GM_Crops_vv__xosyyt.jpg",
    postDate: {
      month: "January",
      day: "09",
      year: "2019",
    },
    authors: ["Sotharyna Nov"],
    category: ["agriculture", "biology", "issue", "chemistry"],
    content: [
      "What is the main purpose of GM crops? The purpose of GM crops is to increase productivity. Using GM crops seems to make life easier and more convenient, crops and livestock could be grown and cultivated with little effort, but things that come easily usually have negative effects. The wide use of GM crops without knowing the long-time risks could have a series of effects on human health, the environment, and the release of toxins into the soil.",
      "The number one most common side effect of consuming GM foods is on human health. GMOs is known as transgenic organism which means that genes from the DNA of one species are extracted and then forced into other genes in a non-natural way (WHO, 2014).  These foreign genes may come from bacteria, viruses, and insects that lead to harmful chemicals in the crops. After the consumption of these crops, a human might have an allergic reaction. This allergic reaction happens when a certain protein or allergen present in the GM crops enters the body and stimulates an immune response. As alluded to earlier, genetically modified foods are created by inserting foreign genes into an organism. And because some inserted genes come from bacteria and viruses, the possibility of the transfer of disease is also being feared. Moreover, studies have shown that genetically modified corn and soy fed to rats led to a higher risk of them developing liver and kidney problems. These health risks may not be transferable to humans, but they illustrate the unpredictable nature of GMOs on living things. There are many more health problems that humans will face. The effectiveness may not be shown up immediately, but after a long-time, this will make our health weaker.",
      "The second negative effect of GM crops is on the environment. The more population has grown, the more food we need. So, to eliminate world hunger and sustain our growing population without depleting all our available land, we need high-yielding crops so we can utilize the land to its fullest potential. However, growing crops on a large scale requires the use of chemicals, such as pesticides, herbicides, and the pollution of aquatic ecosystems. Furthermore, GM crops are usually changed to be insect resistant, virus resistant, or herbicide tolerant. With these changes come some potentially problematic environmental challenges. For example, Bees are hugely important in the pollination of many food crops but are unfortunately extremely endangered by modern agricultural techniques, such as GM crops. In addition, some birds are also at risk from pesticides.",
      "The third negative effect of GM crops is the release of toxins into the soil. The disadvantages of GM crops are much larger than simply harming our health. Regarding its environmental effects, toxicity is a huge issue concerning GM crops. One particular example is the Bt Corn (Bacillus thuringensis Corn), which is widely known for its pest-controlling ability. Bacillus thuringensis is a soil bacterium that has a gene that produces certain protein toxins that effectively destroy pests and insects, like larval caterpillars. This gene is then inserted into the corn to make it more resistant to pests. While such characteristic helps control pests, this may result in the release of the said toxin into the soil. Too many toxins in the soil can prevent the growth of bacteria essential for plant growth. As a result, the soil becomes void of all necessary nutrients.",
      "Furthermore, the long-term effects of GMOs are not certain. Pests that are targeted by these agricultural methods can adapt to pesticides and herbicides, in addition to the DNA changes in GM plants to make them resistant. This means that they will not always be effective, but their toxic legacies will remain. The cumulative effects of products such as GMOs are important to take into consideration. Evidence also suggests that small genetic changes in plants may produce even larger ecological shifts, meaning that there is potential for GMOs to become persistent and weedy in agricultural conditions since they are modified to be resistant to some modern agricultural techniques. This can also mean being invasive in natural settings, where GMOs, of course, do not occur naturally. New, human-modified, plants can become invasive species in delicate, natural ecosystems.",
      "In conclusion, although GM crops provide us with a big number of benefits, they still have an alarmingly negative effect on our health, environment, and the release of toxins into the soil.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Flooding puts people’s lives in danger",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/Flooding_v__lzmwfj.jpg",
    postDate: {
      month: "July",
      day: "16",
      year: "2017",
    },
    authors: ["Zanika Muy"],
    category: ["issue", "agriculture"],
    content: [
      "Flooding has been affecting many resources and every kind of living and nonliving thing around the world such as the lives of people many plants and animals. Flooding is the unusual presence of water on land to a depth that affects normal activities. Most countries in the world are often affected by flooding. Whenever we were talking about flooding everyone will think that it was just a simple issue, but as we already know flooding is the most powerful and dangerous for the population in the country. Flooding has killed millions of people every year. Many people have been dead, gotten sick, lost their job, and lost their valuable thing and their house which is a big cause that government should be protected and concerned about it very well. Many countries around the world have often effect by flooding most of the country have concerned about this disaster so much.  In this case, flooding also has disadvantages and advantages for the world.",
      "Generally flooding come with lots of rain or big rain in the area. Floods can either occur naturally themselves or they can be facilitated by environmental factors that destruction of the flow of water. It will increase the levels of water in the river, lake or in the sea which will cause to any villages around the river or sea. The levels of the water quickly become much higher cause the rain runs into the rivers. Floods also can be the result of the quick melting of winter snows, severe thunderstorms, tropical storms, and other precipitation events. Move on to another point is about floods cause very bad impaction on people. Flooding usually causes people to meet many diseases by drinking and using that water such as fever, or we can call it Water-borne diseases, stomachache and also increase many diseases in your stomach that will lead you to have diarrhea. Standing water caused by heavy rainfall or overflow of rivers can act as breeding sites for mosquitoes, which is lead many children to have the most savage disease called dengue fever. This scary disease can kill children very faster.",
      "Climate-change-related impacts can affect human rights differently. For instance, it is estimated that 85% of people displaced to cause great destruction of floods in Pakistan are women and children. According to UN figures out, there were over 500,000 pregnant women have been affected by the floods which have impressive become worse health conditions in a country that has already one of the highest subject to death rates in the world. Moreover, a 2007 study of weather-related disasters in 141 countries prepare completely convincing evidence to show that gender differences in deaths from natural disasters are directly related to women’s economic and social rights. In reality, women and children seem to be more likely to die than men 14 times in a disaster (Pillay, 2013, p. 247-259). Flooding mostly affects more on children are biologically more sensitive. In this situation, children are at a greater possible loss by disease and most likely drown because they can’t able to swim and somehow can be hit by solid things. Some so many children die from diseases that cause them to have a poor immune system.",
      "According to Climate Change and Children’s Rights: An International Law Perspective, Children also experience psychosocial discontent and emotional commotion during these disasters, which can have a long-term assumption suppose for their health and well-being. A complete effect on the emotional well-being of children is caused by the result of displacement and the actual separation from their parents and their family members. The rate of Children vulnerable to trafficking, violence, and exploitation will get high by not having a social safety net. Climate change also has several indirect effects on children (2013, p. 351-355). Another point is about floods will force people to have a hard living. As we can see most people can’t go to work or run their businesses because of flooding. Moreover, flooding also damages many human houses, building in the city, and animal shelters and all electronic and digital communication seizes. During flooding, most of the roads and bridges are damaged so that people will not be able to go to work or study which is make them waste a lot of time and money. In this case, it will lead to an economic crisis which makes the whole country no development and improvement. Forest help decrease the water going into the city by damaging property and many valuable things. Many tens of thousands of people die every year from weather-related causes. The economic losses due to severe weather are rising sharply.",
      "In addition, the research from Publication title Climate Change, Article/Chapter Title: Climate-Change Effects, Adaptation, and Mitigation conclude that Flooding can be lead to associate an effect with the water resource quality, agriculture, transportation systems, buildings, water treatment plants, sewer systems, and roadways and bridges. During the winter season, the increase in precipitation is forestalled. Flooding might have several kinds of impact on supplies of drinking water, increasing the force exerted on water treatment processes that’s the reason why the extreme weather events are foreseen to harm human health in seventy counties within the state (2014, p.80-85). In fact, In Australia, floods can be one of the most expensive types of natural disaster with management costs estimated over the period starting from 1967 to 2005 averaging at $377 million per year (calculated in 2008 Australian dollars). Until recently, their estimated Australia in 1974 is the most costly year for floods, when floods affecting New South Wales, Victoria, and Queensland outcome in a total cost of $29 billion.",
      "According to more research from Team The WisdomPost & Sophia in Essay, there are three main types of flooding, the first one is Surge floods are floods that occur in the sea coast area due to an increase in volume and tidal changes that occur in the sea or ocean. Hurricanes and storm surge on the sea or ocean can cause lesser, medium, or major floods. The second type of flood is the fluvial flood that occurs by the overflow of rivers. Rivers overflow due to heavy rains that increase levels of the water in rivers beyond their capacity, therefore, resulting in floods. And the third one is pluvial floods. Pluvial floods are caused due to surface water as a result of heavy rainfall. Pluvial floods are destructive because they disrupt the systems of drains and cause an overflow that affects structures.",
      "Last but not least flooding is not all about affecting it, it has some kinds of advantages for the world too. Sometimes it provides many benefits for natural and living things like a tree, many kinds of fish, and a lot of plants. Water improves fish shelter and helps many dead plants like soil to be alive once again. Cities, utilities, reservoir operators, agriculture, and other industries depend on accurate forecasts of water availability. Flooding helps the environment to be clean and safe for the forest to grown faster which is a great shelter for many living things like fish, snails, and seaweed. The benefit of flooding to the farmer is to help the soil to grow faster and provide many nutrients for the soil that were lacking during summer, and also help the forest to grow healthier.",
      "In conclusion, flooding is the most common natural disaster in the world. Floods result from rain, snow, coastal storms, storm surges, and overflows of dams and other water systems. We want to prevent them because they threaten our lives and ways of life. To control flooding, we need to work with the forces of nature, instead of simply trying to eliminate them. Flooding provides a lot of advantages and disadvantages for our society. Flooding damage many building or villages, and affect a lot of living things like human, plants, and many animals. But also benefits many forests, plants under the water, and fish. Flood also heal the earth by decreasing the temperature and saving a lot of plants from lacking water. Overall flooding may occur as an overflow of water from water bodies, such as a river, lake, or ocean, in which the water overtops or breaks levees, resulting in some of that water escaping its usual boundaries, or it may occur due to an accumulation of rainwater on saturated ground in an area flood. People need to be together against flooding.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Is the lack of education the leading cause of poverty in society?",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/Poverty-01_jeoyqc.jpg",
    postDate: {
      month: "June",
      day: "24",
      year: "2012",
    },
    authors: ["Tangnay Ou"],
    category: ["economic", "issue"],
    content: [
      "The link between poverty and education is inseparable because lack of education leads to poverty. Education is referred to the opportunity that every kid and everyone could access to school for primary education, at least they could finish high school. People who get a proper education are literate people while who do not know how to read and write count as illiterate people. If the number of illiterate people is high than the number of literate people, the economy is not good. For example, in Singapore, Switzerland, the United Kingdom, and other developed countries, the number of educated people is higher, and their economy is stable. Proponents say that education is the tool to get people out of poverty. While the opponents say that poverty is caused by lack of health care and disadvantage of the climate or geography of that country. However, the main root of poverty is education because without education people could not get a better job, and the economy of the country will be down.",
      "First of all, education is a wonderful weapon to get better jobs. The people who get a primary education or training skill in school are more likely to get a proper career in the future. For example, some companies and firms, need people who have a degree or certificate to be their employees such as Google, Apple, Microsoft, law firm, and other companies. Going to school to get proper training is a good opportunity to prepare for your future academic career. This fact reflects my belief that people who get a higher education are likely to get higher-paid jobs than those who do not. In addition, the literate people are more confident to look for a better job and do not afraid to negotiate for what is better benefits themselves. They know their rights and the benefit that they should get from the companies or firms. Most of the big companies need people who had a degree and the employee get a better high paid job too.",
      "Second, educated people bend the curve of the economy. For example, the majority of beggars or homeless people are illiterate or school dropout students. Due to this fact, they could not job in their life, so they end up like that. Once the number of beggars or homeless people is higher than normal, the number of illegal activities will increase so the government needs to spend more budget on those issues. As the result, the state’s economy is not growing well. Once educated people get a proper job, they could support their families and send their kids to school, the more money they spend the more tax that the government would get from them. Those educated people are civilized citizens which are less crime in the country too. Furthermore, instead of using the money for the prisoner or others, the government could use all of that tax (money) to build more hospitals, schools, infrastructures, and more investment. These facts show that the literature people could improve the country’s economy.",
      "Some people claim that lack of education is not the cause of poverty because many reasons cause poverty such as lack of clean water and nutritious food. For example, African countries could not fully access clean water because of drought. They believed that this is the reason to cause poverty. That may be so, but education is the main tool to get people out of the property. For example, before 1975, Cambodia was one of the famous countries in ASEAN that had developed infrastructure, and economy, there were so many architects, businessmen, and professors to develop the country. However, during the Khmer Rouge Regime, (3 years 8 months 20 days), millions of educated people were killed by Khmer Rouge Leader. The remained people after the regime were not well-educated people. It takes Cambodia years to build up its education system and the economy. Even though now, Cambodia still improving its education system, allowing every child to go to school and support them to finish high school. As a result, Cambodian people could get a proper jobs and even do the fair international trade stage with other developed countries. It cannot conclude that the disadvantages of the climate and geography of a country are the reason for poverty, while many other reasons cause poverty.",
      "In conclusion, there are many sectors to cause poverty, but education is a powerful tool to break the cycle of poverty in society. Education brings people out of illiteracy; education could make people understand more about their rights and obligation to be civilized citizens. Everyone deserved to have equal access to school and the government should take a proper method to increase the literature number in their country.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title:
      "Do you think online shopping will be the only way to shop in the future?",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956988/InsperU/AMAZON_vvava_zq02q9.jpg",
    postDate: {
      month: "November",
      day: "15",
      year: "2013",
    },
    authors: ["Tangnay Ou"],
    category: ["economic", "technology", "lifestyle"],
    content: [
      "Before when I say, “let’s go shopping!” People will think that I will go to a shopping mall or outlet.  But now things are not the same anymore, everyone is familiar with the term “Online shopping”, online shopping is really popular for this modern and busy lifestyle, there are so many famous E-commerce websites for shopping such as Amazon(USA), Alibaba(China), Gmarket (Korea). Because of the convenience of online shopping, there are three reasons why I believe online shopping is going vital in the future.",
      "The first reason and importance is the convenience of online shopping, people can shop 24/7, at any time, and anywhere. I found this reason is convenient for people who have a busy schedule with work, and people who could not have proper time for shopping at a physical mall. Working 8 hours a day and on weekends, people might want to relax or do something fun with family rather than shopping for their clothes. They have more time to do fun activities with family rather than go to the mall and spend hours choosing what they want and waiting hours to pay at the cashier.",
      "The second reason that I believe online shopping is the diversity of the product. Going online shopping gives so many options to choose from. If you are living in the USA, you can shop for the product in Japan, Korea, India, etc. E-commerce gives you the option to choose plus the price is reasonable for people to afford and some products even provide free shipping and return. In addition, there are so many reviews of the product too. I found this option is great and it gives me the option to choose.",
      "The last reason is no crowd or long queues at cashier or fitting room. Indeed, online shopping does not need to wait in long queues line for a cashier. It is less crowded for people, just click pay then everything your order will be shipped to you. From my own experience, I found that waiting for the cashier unpleased me, and it is time-consuming. Then when I go to the parking lot, sometimes, I forget where I park my car which is another waste of time for me again.",
      "Based on all of those three reasons I believed that online shopping will replace the physical mall. With convenience, variety of products, and less crowd, online shopping will give people more time to do something else besides shopping at physical the mall.",
    ],
    likes: [],
    comments: [],
  },
  {
    id: uuidv4(),
    title: "Amusing ourselves to death response paper",
    image:
      "https://res.cloudinary.com/dgqfcwu7y/image/upload/v1660956989/InsperU/pexels-joy-anne-pura-1186116_girzci.jpg",
    postDate: {
      month: "March",
      day: "14",
      year: "2020",
    },
    authors: ["Meng Huo"],
    category: ["social", "psychology"],
    content: [
      "The main topic that was discussed in the video was “The medium is the message (McLuhan, 1964)”. Me, when I first saw the phrase, I got really confused. In the video, professor McLuhan used the telephone as an example. What I understood from the explanation is that the medium is the connector. So, it is what people use to spread their thoughts and ideas. Whatever sending through this medium creates the environment. And that environment can make an effect on people or the public. For instance, television or radio is what could be called the medium. So, they create a message that can greatly impact audiences much more than the telephone one. Two things stood out for me, which are one the way we expressed is important, and two sometimes it can be misleading if the message is shared by many channels.",
      "What I think about the concept from professor McLuhan is that it is kind of true not only during the time that the video takes place but also during the current generation as well. I like the way he expresses the media by saying “Medium is the message” (McLuhan). It seems to make sense to me now. Now I start to think that some theories misled us to see the medium and the message are not related at all even though they are closely related according to McLuhan. I used to believe that the medium doesn’t matter at all, what matters is what is said or expressed. But I think I was wrong, the way our idea is being shared or spread is as necessary as the message itself. Because the more messages move from one to another the more it changes their meaning.",
      "It is dangerous since it can lead to misunderstanding and miscommunication. It is really useful to know that because next time I will be more careful about what channel I am using to express my opinion. I agree with his opinion about television as well. Though television is now getting less popular, other new media are kind of similar things. It acts as the medium and whatever it does can greatly influence some people. Television can be a new way of creating awareness among the public. Besides, the advertisement was getting popular. It has become an art. Just like other artists, advertisers wanted to make a hook that can catch anyone’s attention. But the way it works can change as the years go by. It was when television was popular, therefore, it can create such a big effect on the message it had.  Another thing about media is that it can alter violence. Since media can manipulate the public, it can cool down the situation with what it says. So, the media can go any way either good or bad.",
      "All in all, I find that the phrase is still relevant to staff with what we are on right now. It tells us that there could be cultural or societal changes with the new and upcoming media that will create the new medium effects. So, we can warn ourselves and seek to understand the new medium beforehand. And the fact that media nowadays can spread quickly whatever we say can easily mislead and lead to many issues, we must be cautious.",
    ],
    likes: [],
    comments: [],
  },
];

module.exports = { articles };
