const articles = [
  {
    title: "Does talent exist or just hardwork?",
    postDate: {
      month: "January",
      day: "19",
      year: "2019",
    },
    authors: ["Leangheng Ou", "Seihakpiseth Tan"],
    category: ["philosophy"],
    content: [
      "We, humans, tend to have unique talents, and that makes us special, that is our asset. Talent is a common word that everyone knows and respects. Most people believe that talent is inborn and the special ability of a person to do something, is the gift that everyone is born with. Do you think what they believe is true? Is talent a gift that everyone gets without doing anything? If it’s true, what were all those talented footballers, basketballers, painters, and musicians doing before their talents were discovered? Were they good at nothing before they found their talents? According to our research and experience, we’ve found that talent doesn’t exist by not doing anything, also three main factors create talents within us, these crucial factors are hard work, environment, and passion.",
      "Hard work refers to the practice, it is the construction of talent. Talent wouldn’t exist in us if we didn’t do anything to achieve it. Talent isn’t a gift, it’s the reward that we receive from practicing. When we practice a lot, our skill and technique will be developed and improve, with better skill and technique, we’ll surely be able to perform better, more skillful, and professional. We’ll additionally gain a lot more experience by practicing, having a lot of experience will expand our knowledge, such as making us be able to think smarter, faster, and more flexible in various situations. Moreover, it boosts our confidence in the field of studies or occupations, it helps us per-forming better when we have strong confidence when we believe in ourselves. Lionel Messi, one of the most famous footballers in the world, five times Ballon d’Or winner, and the player who helped Bar-celona won four Champion Leagues in just 11 years (2004-2015). Messi is the player that defined as talented, gifted because he has the best dribbling skill. When we explore his past, we’ll see that Messi was a kid in Argentina who loved to play football, he started playing when he was around 5 years old, and always loved to show his dribbling skill in the field. In 2000, at the age of 13, Messi moved to Barcelona, one of the best clubs in the world, he started to improve his skill there with other talented kids in the club. In 2008-2009, Messi won his first Ballon d’Or by helping Barcelona to win 6 trophies in a year, including Champion League. After that unforgettable year, most people started to acknowledge Messi’s skills. After his victory, Messi publicly said ‘’I started early, and I stay late, day after day after day, year after year. It took me 17 years and 114 days to become an over-night success.’’ Messi proves that without his hard work, his talent and success wouldn’t exist. We tend to look at what he has rather than how he achieved it. We only see him when he’s on the top of the mountain, but never noticed him when he was climbing.",
      " ‘’If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all.’’ – Michelangelo",
      "Another factor is the environment; it also plays an important role in improving talent. For instance, if children were raised in a singer family, those children will most likely are going to be singers in the future because of what their parents influence them. Children are like papers, they can get stained, cut, and folded pretty easily so, if they see their parents doing something over and over again, they will try to mimic them. Another positive reason is environment can as well sharpen their way of thinking and the way they interact in the real world. Michelangelo was one of the greatest artists of his time, he was born in the Republic of Florence during the High Renaissance. Considered by many the greatest artist of his lifetime, and by some the greatest artist of all time, his artistic versatility was of such a high order that he is often considered a contender for the title of the archetypal Renaissance man, along with his rival, the fellow Florentine and client of the Medici, Leonardo da Vinci. Michelangelo was influenced by many artists throughout his career. Although he preferred to tell people that he was self-taught there were those along the way who helped to shape his skills. For example, at a young age Michelangelo worked under the great Florentine sculptor Domenico Ghirlandaio, who helped to form Michelangelo’s opinions about art, and taught him different drawing methods. Due to the environment that Michelangelo was raised that turned him into a great artist. Environment can also influence our passion. If our passion is painting, then our environment can also be one of the factors that helps us sharpening our passion. Salvador Dali, one of the most famous surrealist painter in the his-tory. Dali was born in Spain, the place where many spectacular and brilliant artworks located in, he also was born during the era that paintings were so popular, so precious for most people. This led him to observe and obsess with painting because of the influence, inspiration, and the impact from his envi-ronment since he was around 6 years old. When he was 12 years old, Dali started to learn how to paint at the drawing school called Colegio de Hermanos-Maristas and the Instituto. Due to the inspiration and influence by famous artists that were in his era, Sal-vador Dali was became so passionate with art, and soon became the famous artist in Spain. ",

      "Last factor is passion, it’s certainly true, that most of A, B students are the students who have love study-ing, who take things very serious on their lessons, who always pay attention while learning. While C, D, E students are the students who enjoy doing differ-ent stuffs, such as hanging out, playing video games. This is passion is all about, passion is the factor that motivates us to work hard and give everything we have to what we love. Hard work without passion is like a great hunter without good equipment, when a decent hunter goes hunting without equipment he needs, he might not be able to hunt animals effec-tively like other hunters who have equipment. Simi-lar to the guy who works really hard without passion, he won’t improve his skill effectively like the person who has, because he doesn’t have motivation, inten-tion in doing it. This is why some people spent the large amount of their life practicing but still not fruit-fully improve like others, because they don’t spend all their attention to what they learn. ‘’I have no special talent, but I am just passionately curious’’ –Albert Einstein When we love something, we tend to focus, pay all our attention and do it with strong intention, with love, we take thing seriously without noticing on it, and these actions will cause our skill to improve rapidly and effectively than others. This is why most talented people seems to fall in love with their talent, and this is the reason why they got their talent. If we ask talent painters about how they are so good at painting, they might say ‘’I have been practicing for a long time, and I love painting.’’, and if we ask Messi how he become so good at footballing, he must say ‘’Because I love playing it’’ The famous tennis player named Roger Federer once advised to young players about how to reach their dreams, mentioned ‘’First, you have to have a passion for the game’’ In short, passion is the factor that pushes us to work hard to attain what we aimed, and the factors that push-es us to give everything while we trying to achieve, it’s the inside power. Without passion, there will be no motivation, without motivation there will be no inside power. Yanni Chryssomallis, a famous Greek self-taught pianist, and composer said ‘’All you need is passion. If you have a passion for something, you’ll create the talent.’’",
      "In conclusion, talent is special aptitude that everyone possesses it. Not everyone is already born a scien-tist, doctor, footballer or singer, yet as human beings, we can develop our talents to fit in different catego-ries. In our ideas, we have come up with a cycle of talent: it starts with environment, up to the passion, till hard work and back to environment again. The reason is that we contemplate they are related to each other, if one of them was out of the picture, the other two wouldn’t correlate with each other. Never-theless, as we read the paragraphs above, there are enough evidence to prove that talent wouldn’t exist without doing anything, it’s not a gift from the god that sent to everyone. However, talent is the combi-nation of three factors, hard-work, environment, and passion.",
      "‘’There’s no talent here, this is hard work. This is an obsession. Talent does not exist, we are all equals as human beings, you could be anyone if you put in the time. You will reach the top, and that’s that. I am not talented, I am obsessed.”  - Connor McGregor",
    ],
    like: 5,
    comments: [],
  },
  {
    title: "Three smart goals to help you accomplish your ideal life",
    postDate: {
      month: "May",
      day: "15",
      year: "2018",
    },
    authors: ["Tola Ouk"],
    category: ["philosophy", "personal development"],
    content: [
      "Commitment here refers to the ability in which I can attach the goal and my determination to reach it even when I face obstacles. I believe that goal and performance are strongest and most effective when we are committed, and even more so, we might think that goals are difficult. I think that in the presence of strong commitment, there will be a significant relationship between goals and performance; I strongly believe that in order to be successful, we must have a strong desire and a comprehensive understanding of what is required to achieve it.",
      "When a goal is too general, it can limit our motivation value which will make us lose interest in attaining the goal that we want to achieve. Therefore, I think that setting a specific goal will put me on a direct course. I plan on setting clear and precise goals that can be measurable with KPI. Key Performance Indicator is really important for me because it lets me see my progress and where I am at which point.",
      "In order to have a stable job, I think that it is absolutely important to make as many connections as possible because when people know you for a long time, they can recommend jobs that are well suited to your ability. I can do that with online social media platforms these days such as Facebook and especially Linkedin which is getting more famous among the new generation. By establishing my own identity and profile, I can now use these tools to help me spread and advertise myself much better and easier.",
    ],
    like: 8,
    comments: [],
  },
  {
    title: "Globalization is important for any countries in the world",
    postDate: {
      month: "April",
      day: "25",
      year: "2020",
    },
    authors: ["Tola Ouk"],
    category: ["social", "economic"],
    content: [
      "Over the last two decades, our society has witnessed unprecedented changes in the overwhelming trend of globalization. From the traditional water festival to the western white Christmas. From the family-centered cultures to the more independent living style. It is undeniable that globalization is slowly taking all over the world bit by bit. However, the influences of globalization are not all bad, because the positive effects of globalization cannot be neglected.",
      "Globalization benefits us in far wider ranges. Ever seen the accelerated development of globalization, mankind is introduced to new tools and technologies including credit cards, medicines, and most importantly the internet, etc. Globalization is not only changing for the better but it is also an opportunity. It is an opportunity to make improvements on our parts, to keep pace with the other developed countries and it is an opportunity to present to the whole world the merit of our culture.",
      "In addition, it seems meaningless whether our traditional value is better or western’s is better. What is important is the selection process. What we should do is absorb the essence and desert the dregs, why do not we consider it as critical assimilation? Imagine if the essence of different cultures and values are collected and combined with that of our own, we cannot only possess the incredible traditional culture that has instructed and inspired hundreds of generations of our own country. But on the quintessence of other cultures some having been cultivated over the long course of history. As for us people of the 21st century, we can see the drastic innovation the society has been undergoing and the current circumstance can bring about rap-id development to the culture of our society if dealt with appropriately.",
      "In conclusion, globalization brings many benefits along with it, from modern technologies to presenting the world of our own culture. Therefore every country needs globalization because it will help us in time turn our culture into a more civilized one.",
    ],
    like: 8,
    comments: [],
  },
  {
    title: "The effect of social media to the young consumers",
    postDate: {
      month: "March",
      day: "10",
      year: "2018",
    },
    authors: ["Meng Huo", "Tola Ouk", "Eakseng Meng"],
    category: ["social"],
    content: [
      "Business marketing is constantly renewed to create new concepts and strategies every single day. It is in this context that digital marketing has emerged as one of the largest areas of business marketing. Its existence has proven to be very crucial for the growth of the due to the new area of business: to be focused on the producer now directed towards the customer. That has been noticeable in revolution over the last half-century. Besides this, there has been a continuous flow of advanced technology. The possibilities in all parts of knowledge have been increased because of the technological development in Cambodia. It was not difficult to foresee: joining marketing technology and increasing its strength as a tool for marketing. With the advent of the Internet, the rise of e-mail, new media communication, and computing expansion some of the elements are pushed to maximize their potential.",
      "The target of young consumers in Phnom Penh is the easiest to persuade in digital marketing. And the use of social media is an innate part of them. For this reason, the mobile phone has become a vital device entering this industry. Many studies conducted had mentioned that it is increasingly clear that the mobile has a predominant role in the life of buyers. The proportion of users who uses the phone for entertainment purpose has increased three times, in the last decade. Youth in Phnom Penh is the main user of the new media from the development of new technologies and therefore one of the most important objectives of the strategy’s companies advertising in the media.",
      "In Phnom Penh, the youth is segmented from young adults to the so-called Generation Z, which is one of the most in the crosshairs of traders in recent decades. New media is used by this segment primarily for entertainment rather than information. Social media are becoming increasingly important since the 2000s, especially Facebook and Instagram. They also download videos and music, watch videos and TV online, play, and do online shopping. Notably, increased activities relate directly to Facebook.",
      "As a result of this, companies have had to adapt their advertising communication to this segment in several respects. By using social media as a platform for digital marketing; there can be a reduction in the expense of traditional advertisement. Moreover, it can help build brand awareness; digital marketing can significantly increase traffic to a site to generate more customers. Therefore, social media is undoubtedly one of the best channels for digital marketing.",
    ],
    like: 3,
    comments: [],
  },
  {
    title: "The un-talk culture of salary",
    postDate: {
      month: "March",
      day: "18",
      year: "2021",
    },
    authors: ["Chirika Phang Lee"],
    category: ["Job", "social"],
    content: [
      "I got the shocked of my life when Igot my first intern job last years, that you don’t discussabout your sala-ryor your co-worker salary with each other,nomatter how close you are with them. It’s like a culture or a rule. It’s like it wrong to find out that you might make more or less than your co-worker. Peoplewon’t tell you it bad or offensiveto askabout it,they will glareat you, like you break some rule that you shouldknow. The reason Iask other co-worker about their salary is to know how much they made when they got the same job and join to work as the same time as me. Is this person pay more than me why, what this per-son have or do to germore pay, or why is this person getpay less than me.And alsoIwantto know is there a pay gap as the same at foreigncountieswhere men are being paid more than woman. But Iwill nev-er know about that now.Irealize that adult that are workingfor 3 to 5 years now that they don’tshare how much they make to their close friends. When ask “why?”they replythat it weirdto take about, andwhat happenedtheymake less it embarrassed!Ialsostart tobelievepeopledoesn’t want to share about how much they got paid is becausethey afraidthat other will start to ask for something from them and treat them differently and when they brokeor aren’t willing to helppeople will turnon them. Well Ibelieve people should talk and share about their payment, so fresh graduatecan preparethemselves for what to come and because you might not know thatsomeone or maybe even you are being taking advantage.",
    ],
    like: 9,
    comments: [],
  },

  {
    title:
      "Are cultural dimensions mentioned in the book practically accurate?",
    postDate: {
      month: "June",
      day: "05",
      year: "2021",
    },
    authors: ["Meng Huo"],
    category: ["Culture"],
    content: [
      `Well, I agree with Erin for the most part, however, I believe that it leads to "stereotypes". I remember when I was discussing with my German friend, Mitchel (I probably spelled his name wrong), he mentioned that as a German, there are many stereo-types about his culture which are inaccurately stat-ed. For instance, he wasn't that serious (German is a stereotype as serious/strict), he made jokes, is playful, and is a very open person. This tells me that I can’t just depend on this cultural theory I learn because it depends on the person individually. With respect, I am not saying what Erin wrote is misleading, but rather it is overused to the point where it becomes inaccurate. Anyway, this book has so many great insights that catch my attention. Besides, most of the main ideas in the book are easy to understand since it is mostly discussed in the lecture. And, here are the top 5 insights /quotes for me; "Kuuki Yomenai", "How to feedback", "Working in the group", "Guanxi", and "How late is late".`,
      "First of all, the Japanese phrase, “Kuuki Yomenai”, means can’t or unable to read the air. It caught my attention the first time I read it because I could re-call back during the Japanese guest speaker. I believe she mentioned that same phrase, which she mentioned that environment/surrounding plays an important role in the conversation with high context culture. I agree with the author about this idea, but I noticed that the book considered most European countries as low context, which I have experienced otherwise. During my fall semester in Lithuania, many of my European friends did know how to read air. For example, when we were discussing our countries, Alexander (Lithuanian) always compliment Cambodia whenever I sound excited over my statement. I think he read my tone of voice and facial expression. So, to me, saying that low context culture can’t read air is not entirely true, but in most cases it is true.",
      "Second, how to give feedback. With all the technologies, globalization has become more common; working in an international group happens quite often. Erin mentioned that in this kind of situation, feedback is very important. She explained that some cultures prefer direct feedback, while some cultures don’t like being confronted, thus preferring indirect feedback. I agree with the author in this aspect because I have seen both types of cultures. From my experience, German would take any form of feedback without getting offended. When I work with them, they would constantly ask me, “what do you think?” On the other hand, when I give an idea they would feedback immediately. If they liked the idea, they said “smart”, if not, they said, “how about this…?” Spanish is on the opposite side; my Spanish friend would always say “perfect” to any of my ideas. I don’t know if that is true for all Spanish but that is definitely how I experience Spain culture. Moreover, when I work with Ukrainians, they would work quickly and finish as soon as possible. Then, the feedback part would come after everything was finished. The way they do it, they vote to keep it (if it is good) and vote to remove it (if it is bad). Overall, Erin is right, for me (indirect culture), I sometimes feel down cause of how others give feedback, but after a while, I adjusted and worked with them smoothly.",
      "The third aspect is working in a group. The author divides the leading system in a group into 2 different styles, Egalitarian and Hierarchical culture. Based on my understanding, I think Cambodia is probably a hierarchical culture. So, whenever I work in a group, I expect my team to have a leader. However, it wasn’t the case when I did my assignment during my exchange semester. All the teams I worked with don’t care about who was the leader. I thought it is impossible to work without someone to lead, but it was quite better without a leader in some circumstances. By working closely together with everyone having equal power, the workflow goes smoothly. I am not saying that hierarchical is bad, but I would prefer Egalitarian overall. Ultimately, it is not about which is better but rather understanding both concepts to avoid making mistakes unintentionally.",
      "Fourth, is the Guanxi effect. The author stated this Chinese word to explain how trust works in China. The reason I am interested in this concept is that I have experienced this before. The first time I met my Chinese friend, Joe, he was even more serious than the German gentlemen. But after some time, he started to be more open and talkative. This might also fall into the definition of coconut culture. I remembered one-time Joe even said, “Chinese doesn’t make a joke.” I and other friends were like “What??” So, he explained that they only joke around close friends or family, unless there is a lot of trust in the relationship, the Chinese tend to be holding back.",
      "Lastly, the time concept of culture. In the book, there are 2 main concepts: Linear time and flexible time. I thought it is interesting because not only do different countries have different time rules, there is an influence between them. Meaning that after some time one culture can change another culture. To elaborate, I had a few trips with the exchange students’ group, which includes many nations such as Cambodian, Chinese, German, Georgian, French, Belgian, Spanish, Malaysia, and American. Out of all, the 2 Spanish guys always appear last on any trip. They are always 15-30 minutes behind others. I don’t mind that because it happens every day in Cambodia. But what is interesting here, after a few trips I noticed that the German guy also appears late with the Spanish guy. Hence, it is clear that a person of one culture can influence another person of a different culture to follow.",
      "To sum up, I wish I had read this book before my exchange program because I would have adjusted better and made fewer mistakes. Though it is not the end of the world to commit cultural mistakes, it is the best way to learn a culture, in my opinion. All information in this book is absolutely helpful for anyone as it is easy to understand and relatable. There are many more cultural aspects that are yet to be explored. I would say let’s go out there and talk with other cultures and find it out.",
    ],
    like: 21,
    comments: [],
  },

  {
    title: "Human communications are more revealed in body language",
    postDate: {
      month: "July",
      day: "27",
      year: "2021",
    },
    authors: ["Leangheng Ou"],
    category: ["psychology", "social"],
    content: [
      "When we are unhappy with someone during the conversation we would pretend that everything is okay and hide our true feeling by muting statements that we wish we could let out. In most conversations, we try to be nice as we possibly could. Giving positive feedback, avoiding making judgments, and more. During difficult conversations with our co-workers or business partner, we don’t want to let the anger out cause it could potentially sabotage the relationship.",
      "Yet, there are still some parts of us that we are not in control of all the time. Our body keeps sending signs even when we try to lie. Our tone of voice could turn aggressive when we are mad, and soft when we felt weak. These reactions on some occasions are hard to respond to so hide them away. Because the body muscle needs its way to relieve the tension.",
      "For example, a woman suddenly uses an aggressive tone of voice while saying polite words during the conflict. Another example is a man always touching his ear when being asked if he stole something or did some crime. Mostly, when a person always touching their ear or neck it’s a sign showing they are nervous and trying to hide something.",
      "Words are tools to lie and deceive people. It is used to manipulate others to serve our interests. A person could say anything we want in an instant.  That is why we should pay more attention to body language, facial expression, and tone of voice instead of putting our trust in the words people say.",
    ],
    like: 35,
    comments: [],
  },
  {
    title: "The impact of industrial revolution",
    postDate: {
      month: "June",
      day: "13",
      year: "2019",
    },
    authors: ["Tola Ouk"],
    category: ["technology", "economic"],
    content: [
      "As the world is shaping itself rapidly every single day, so is industry. Mankind is being led to a more sophisticated life. The first industrial revolution started in the 1760s and it has altered the way people work as well as the entire productions themselves in any industry. Industry 4.0 is about connectivity, it is an opportunity to radically shape the way industry responds to the needs of society. In this essay, we will examine the impacts of industry 4.0 in 2 main areas which are economic and environmental.",
      "To begin with, the introduction of industry 4.0, helps a lot in the economic sector mainly the decreasing cost of production. Companies nowadays are seeking many opportunities from three-dimensional printing. Those companies have just begun to adopt additive manufacturing, such as 3-D printing. These 3D printing machines can be used in so many different ways but mostly, for prototyping and producing individual components. With industry 4.0, these types of technology are getting cheaper and more affordable because of the higher demand from the market, especially in the field of innovation and entrepreneurship. According to an online article, it mentioned that companies such as aerospace are already using additive manufacturing to apply to new designs (Lorenz, 2015, para. 9). This approach could reduce the aircraft weight, lowering their expenses for raw materials such as titanium. This new technology will be very helpful in economic growth as well mainly in reducing transport distances and stock on hand.",
      "Secondly, corporate social responsibility (CSR) has been an important part of any company these days because it is a way for companies to show off their activities and what they have done for society to the public. Moreover, based on an online article from the University of Applied Sciences, predicted that companies can implement more efficient energy management (Gabriel & Pessl, 2016, p. 141). The new industry 4.0 facilitates greater transparency in the energy system of a company. “ Smart grids’’ help the company to better understand how their energy consumption is being used and whether it is effective and efficient enough (Castagna, 2019, para. 1) This can reduce energy costs and extend the life cycle of the user devices (Jasperneite/Bretschneider 2013). In addition to saving the environment, transportation also plays an important part since we are living in a globalized world where people buy so many cars in which this activity affects releases carbon dioxide into the air which damages the earth. Now, with industry 4.0, everywhere can be easily accessed in a short time and convenience. More people are starting to realize that they do not have to buy a car anymore to travel to work or anywhere. According to economic-forum.com, as traffic congestion continues to grow more and more in urban areas, more citizens have realized that the government should invest more money in public transport modes, such as metro trains, bus rapid transit systems (BRT) or buses, instead of personal vehicles (Fang, 2015, para. 1).",
      "In conclusion, the industrial revolution will bring about major changes to the world we live in today. It will not only make the lives of the citizens more convenient and accessible but also contribute to the environment as well. From steam-powered to the mass production model that dominated the second, or even the emergence of computer-driven systems from the third revolution that we are living in today. This new industry 4.0 will help shape the world into a ‘’gig economy’’ where people can work from home or anywhere they want to without having to travel far.",
    ],
    like: 23,
    comments: [],
  },
  {
    title: "The feeding frenzy",
    postDate: {
      month: "October",
      day: "02",
      year: "2017",
    },
    authors: ["Alyssa-Jayne Tain"],
    category: ["social"],
    content: [
      "Over the past three decades, obesity-related health problems, such as coronary heart disease, cancer, and type 2 diabetes, have been continuously rising. These health problems are clearly all related to food consumption, meaning that our current society has a major dieting issue. Such, Feeding Frenzy discusses the huge role that food industries play in making up our society’s overall health. In fact, despite the media’s constant focus on how obesity is a personal failure and that with the right diet and the right amount of effort, it can be overcome, 1/3 of Americans are obese. Therefore, this isn’t about an individual’s willpower to change, this is about how obesity has become a societal problem, mainly due to marketing from the food industry. The documentary showcases how our capitalistic society has led to food industries being money-driven and, such, causing major health crises. The food section has largely been able to achieve its goals through its diverse marketing strategies. For example, many companies try to associate their foods with the most important moments in people’s lives (Coca-Cola advertisement). Supermarkets are also always arranged in long hallways filled with products and escape routes, obliging customers to walk through the whole hallway, which increases the chances of bigger purchases. Furthermore, processed foods are usually genetically modified and contain a lot of chemicals. They are also sold at a much cheaper price than foods that do not contain as many chemicals. , because there is so much distance, mentally and physically, between these processed foods and the consumers, customers just end up choosing the cheaper options, which encourages industries to sell more cheap processed foods. In other words, the food industry is willing to do whatever it takes to get clients even at the cost of a whole population’s health.",
      "Such, I do think that the documentary is right blaming our current society’s obesity-related problems on the food industry. This has indeed become a societal problem when 1 out of 3 Americans are obese. I believe that it is important to also let others know that this isn’t just about personal responsibility. An individual shouldn’t be entirely disappointed by their weak willpower, as this is the actually-major problem caused by our money-hungry society. What’s as scary as our growing health problems is the food industry’s marketing system. The fact that food industries would do anything to get customers is honestly very disturbing. For example, many companies create, for the customers, an illusion of health by creating green-colored labels, inserting words such as “natural” and “whole wheat” onto their cover, and inferring health claims. Moreover, most advertisements are targeted toward children, as they have large spending power and purchasing influence. As well, children could be conditioned to become loyal consumers. Additionally, the products that are constantly being sold and marketed are incredibly bad for the consumers’ health. These products contain huge amounts of sugar and, consequently, make self-control very difficult to achieve. For example, Doritos are made so that you can’t just have one bite. Even educated people on this matter have a hard time avoiding junk food. Portion sizes have also grown, making self-control even more difficult.",
      "I do find scary the degree to which companies are willing to take to get people to purchase their products. Regrettably, I think that the only way to solve this is to completely change our political system into one less axed upon maximum profit.",
    ],
    like: 68,
    comments: [],
  },

  {
    title: "The three habits of creative people",
    postDate: {
      month: "March",
      day: "01",
      year: "2019",
    },
    authors: ["Leangheng Ou", "Seihakpiseth Tan"],
    category: ["personal development"],
    content: [
      "Creativity is a powerful weapon used by all living things, not only us, humans, but animals too. To simplify this, creativity is the act of making or in-novate something new based on ideas. Most of us consider artists or writers are highly creative people. However, creative ideas can just pop up out of nowhere, and sometimes we don’t even realize it. Creative people tend to have unique habits that made their minds into thinking more creatively. The question has risen what are those habits? And what can we do if we want to be like them? Based on our observation in the past, we’ve found that everyone can be creative, and everyone can be like anyone. We’ve found that creative people tend to have three different habits that most people don’t. There are thinking beyond their limitation, think differently from others, and are willing to show their ideas to the whole world without any hesitation.",
      "Firstly, creative people tend to think about something that doesn’t exist yet. They aren’t interested in doing what the world has already done, but they like doing something that the world hasn’t done yet. As we can see, when we look at creative things such as television, smartphones, computers, cars, cameras, or light bulbs, those are the things that people 1000 years ago couldn’t imagine and would never dream about. The fact is, that kind of stuff is always found by the people who have unimaginable ideas. For example, Steve Jobs was one of the most influential people in the world. Steve Jobs was the man that tried to do something that people in his time couldn’t believe, something that changed the world. He was the founder of a computer called Macintosh, it was the first computer that ever made included a mouse which makes it easy and comfortable for most people to use the computer. He also invented the first touch screen or called the smartphone. His ideas and invention have impacted the world a lot, such as the way we work, study, and communicate with others. Because of his unbelievable ideas, Steve became so successful and was recognized as one of the most creative people in the world. And of course, there are a lot more creative people like Steve Jobs such as Nikola Tesla, and Thomas Edison that invented unimaginable things in history. Neville Goddard, the famous spiritual philosopher of the 20th century once said ‘’There is no limit to your creative power’’. It is true that creativity no has a limit. Inside the mind of creative people, they always think that stuff we already intended has a limit, but the stuff that hasn’t been intended for us has no limit. This is why they like to think and do something that most people can’t believe, something that is beyond the limitations of others' imagination. And, we think it right to say creative people don’t like to follow the world, but they like the world to follow them.",
      "Secondly, if you also do the same old thing, and follow the same old path, you are not creative at all. Creative people are prone to think differently from others. They sometimes are the biggest enemies of the same old paths. An American journalist Bill Moyers said ‘’Creativity is piercing the mundane to find the marvelous.’’ Creative people like to change ordinary things to another level. If the current path is simple, they’ll try to change it to match their uniqueness, If the current path is boring, they’ll try to change it to be interesting, if the path is difficult, they will strive to make it easier. Therefore, this kind of habit leads and inspires those creative people to often come up with new ideas in their workplaces. However, inside most normal people’s minds, they always say ‘’Let's do this way, this is the safe way’’ or ‘’Just follow what he/she said because he/she has done it safely’’, or ‘’ We have to do this way, this is the only way.’’ Creative people, always think differently from them. Creative people are willing to take risks when doing things differently from others. The sentence that creative people usually use is, ‘’I think we also have another way.’’ Miyamoto Musashi, the Japanese philosopher stated ‘’ There is more than one path to the top of the mountain.” There is no limitation inside the mind of creative people, and there is always more than one way. All in all, the habit of enduring in thinking differently from others will always influence us to find different ideas from the existing ideas and soon known as new ideas.",
      "Thirdly, they are the type to show how confident they are when it comes to idea sharing.  However, most creative people’s mindsets tend to not involve in the crowd that much because unnecessarily conversations are not for them. Nevertheless, being an introvert person or extrovert person doesn’t mean you’re creative. According to research, our DNA is probably most responsible for being creative or not.  if some creative people are introverts, we can’t consider them rude or mean people just because they don’t socialize as extroverts do. Nonetheless, when it comes to ideas, they are always open up and always trying to learn new things. Additionally, having those creative people in a team will make the discussion even better.  Elanor Roosevelt said, “Great minds discuss ideas; average minds discuss events; small minds discuss people.” For example, Mark Zuckerberg, is an American technology entrepreneur, philanthropist as well as the founder of Facebook. He is one of the most creative people based on his creation, Facebook. Another example is Steve Jobs, Jobs was the founder of Apple, and he also shared his idea through inventions and Apple products. He wasn’t the type to let his body wander around, just his mind that was wandering around, That’s why he came up with Apple.",
      "In conclusion, every one of us has our uniqueness as well as our creativity. Being an intelligent individual doesn’t mean you have a creative mind. On the hand, being a creative person doesn’t mean you are smart, it means you are more governed in the way you are thinking. Those three habits that we have mentioned above are established by our experiences and points of view, there are more ways to be creative. Like Albert Einstein once said,” Creativity is contagious, pass it on”.",
    ],
    like: 27,
    comments: [],
  },
];
